[package]
name = "unarm-generator"
version = "0.6.0"
edition = "2021"
authors = ["Aetias <aetias@outlook.com>"]
license = "MIT"
description = "Generates Rust code for unarm"
repository = "https://github.com/AetiasHax/unarm"
publish = false

[dependencies]
anyhow = "1.0.82"
prettyplease = "0.2.19"
proc-macro2 = "1.0.81"
quote = "1.0.36"
regex = "1.10.4"
serde = { version = "1.0.200", features = ["derive"] }
serde_yml = "0.0.5"
syn = { version = "2.0.60", features = ["full", "visit-mut"] }
