[package]
name = "unarm-fuzz"
version = "2.0.0"
edition = "2021"
authors = ["Aetias <aetias@outlook.com>"]
license = "MIT"
description = "Fuzzer for unarm"
repository = "https://github.com/AetiasHax/unarm"
publish = false

[dependencies]
num_cpus = "1.16.0"
unarm = { path = "../disasm" }
